name: PF2e Workbench CI

on:
  workflow_dispatch:
  workflow_call:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Check checkout
        run: |
          git submodule status
          ls -R submodules

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install NPM Deps
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Show result
        run: ls -R dist/packs
